### ISSUE TITLE
Use Python to write a program that resizes images

### ISSUE THREAD

**Issue by MasonDev-97** [MasonDev-97/Resize_images#1]
I have an assignment using YOLOv10 to train a model to detect and distinguish between dogs and cats. 
Currently, I am facing some image size issues because they are not the same size, so I cannot train the model. 
I would like your help in writing a Python program (which can be used in Pycharm) to resize the existing images in the datasets. I want the image size to have a width of 640, and the height will be calculated based on the width.

**Comment by tratlamtruong** [comment]
I would like to apply to this issue, can you assign it to me? @MasonDev-97

**Comment by MasonDev-97** [comment]
Hello @tratlamtruong, I've assigned to you.

**Comment by tratlamtruong** [comment]
Thanks @MasonDev-97. I've pulled up my code, when you use this code, change the two reference pairs to source_folder and destination_folder. Src folder is where you save the image (not resized), des folder is where you want to save the image (resized). Please let me know if there is any problem and I will help you.

**Comment by MasonDev-97** [comment]
I have checked your code. Thanks.
